name: lwm

# docs: https://kramdown.gettalong.org/quickref.html
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-sitemap

permalink: /:categories/:year-:month-:day-:title:output_ext

encoding: utf-8

timezone: CN

excerpt_separator: <!-- more -->

# 计划用这个来实现 别人帮助 编辑
doc_url_path: https://github.com/R32/r32.github.io/blob/master/


##### custom metadatas

powered_by:
  - name: Github Pages
    url: pages.github.com
  - name: Bootstrap v3
    url: v3.bootcss.com
